name: Deploy ui.sagtech.io
run-name: Deploy ui.sagtech.io. Pushed into main by ${{ github.actor }}.

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: remote commands on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd repos/Sagtech-UI
            git pull
            sudo docker compose up -d --build
            sudo docker image prune -f
